## Pandasa giriş

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#seriler tek boyutludur
s = pd.Series([10,20,30,40],index = ["a","b","c","d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
# dataframe iki boyutludur
data = {
    "isim": ["ali","ayşe","mehmet"],
    "yas": [25,30,22],
    "sehir": ["istanbul","ankara","izmir"]
}
df = pd.DataFrame(data)
df

     isim  yas     sehir
0     ali   25  istanbul
1    ayşe   30    ankara
2  mehmet   22     izmir

In [ ]:
print(f"Şekil (satır,sütün): {df.shape}")
print(f"Sütün isimleri: {df.columns}")
print(f"İndeksler: {df.index}")
print(f"veri tipi: {df.dtypes}")

Şekil (satır,sütün): (3, 3)
Sütün isimleri: Index(['isim', 'yas', 'sehir'], dtype='object')
İndeksler: RangeIndex(start=0, stop=3, step=1)
veri tipi: isim     object
yas       int64
sehir    object
dtype: object

## Pandas Seriler

In [ ]:
s1 = pd.Series([10,20,30,40]) #listeden seri oluşturma
s1

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s2 = pd.Series([10,20,30,40],index=["a","b","c","d"])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
data = {"Ali": 55, "Ayşe":45, "Mehmet":25}
s3 = pd.Series(data)
s3

Ali       55
Ayşe      45
Mehmet    25
dtype: int64

In [ ]:
s = pd.Series([10,20,30,40],index=["a","b","c","d"])
print(f"Değerler: {s.values}")
print(f"İndeksler: {s.index}")
print(f"Veri Tipi: {s.dtype}")
print(f"Boyut: {s.shape}")

Değerler: [10 20 30 40]
İndeksler: Index(['a', 'b', 'c', 'd'], dtype='object')
Veri Tipi: int64
Boyut: (4,)

In [ ]:
print(s["b"])
print(s["a":"c"])
print(s[0:2])

20
a    10
b    20
c    30
dtype: int64
a    10
b    20
dtype: int64

In [ ]:
print(f"Toplam: {s.sum()}")

Toplam: 100

In [ ]:
s = pd.Series([10,20,30,30,30,50,50])
print(s.unique())
print(s.value_counts())

[10 20 30 50]
30    3
50    2
20    1
10    1
Name: count, dtype: int64

## Pandas Dataframe

In [ ]:
data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
df

     isim  yas     sehir
0     Ali   25  İstanbul
1    Ayşe   30    Ankara
2  Mehmet   22     İzmir

In [ ]:
arr = np.array([[1,"Ali",25],[2,"Ayşe",30],[3,"Mehmet",22]])
df = pd.DataFrame(arr,columns=["id","isim","yas"])
df

  id    isim yas
0  1     Ali  25
1  2    Ayşe  30
2  3  Mehmet  22

In [ ]:
# satır ve sütün seçimleri

print(df["yas"])
print(df.loc[:,"yas"])

0    25
1    30
2    22
Name: yas, dtype: object
0    25
1    30
2    22
Name: yas, dtype: object

In [ ]:
print(df[["isim","yas"]])
print(df.loc[:,["isim","yas"]])

     isim yas
0     Ali  25
1    Ayşe  30
2  Mehmet  22
     isim yas
0     Ali  25
1    Ayşe  30
2  Mehmet  22

In [ ]:
#sütün ekleme ve sütün silme
df["puan"] = [80,90,85]
df

  id    isim yas  puan
0  1     Ali  25    80
1  2    Ayşe  30    90
2  3  Mehmet  22    85

In [ ]:
df.drop("yas",axis=1,inplace=True) #axis = 1 -> sütün sil demek
df

  id    isim  puan
0  1     Ali    80
1  2    Ayşe    90
2  3  Mehmet    85

## Veri Kaydetme ve Okuma

In [ ]:
data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
# kaydet
df.to_csv("ogrenciler.csv",index=False)
df.to_excel("ogrenciler.xlsx",index=False)
df.to_json("ogrenciler.json",orient="records",lines=True)

In [ ]:
#tekrar oku
df1 = pd.read_csv("ogrenciler.csv")
df2 = pd.read_excel("ogrenciler.xlsx")
df3 = pd.read_json("ogrenciler.json",lines=True)

     isim  yas     sehir
0     Ali   25  İstanbul
1    Ayşe   30    Ankara
2  Mehmet   22     İzmir

## Veri inceleme ve özetleme

In [ ]:
# ilk ve son satırlara bakmak
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
print(df.head(3)) #ilk x satır
print(df.tail(3)) #son x satır

     isim  yas  not
2  mehmet   22   75
3  zeynep   28   95
4   burak   27   85

In [ ]:
# genel bilgiler
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())

(5, 3)
Index(['isim', 'yas', 'not'], dtype='object')
isim    object
yas      int64
not      int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   isim    5 non-null      object
 1   yas     5 non-null      int64
 2   not     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [ ]:
#temel istatiksel analiz
print(df.describe())

            yas        not
count   5.00000   5.000000
mean   26.40000  85.000000
std     3.04959   7.905694
min    22.00000  75.000000
25%    25.00000  80.000000
50%    27.00000  85.000000
75%    28.00000  90.000000
max    30.00000  95.000000

In [ ]:
print(df.isnull()) #eksik değer var mı
print(df.isnull().sum()) #her sütundaki eksik değer sayısı

    isim    yas    not
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
isim    0
yas     0
not     0
dtype: int64

In [ ]:
df.loc[2,"not"] = None
print(df.isnull())
print(df.isnull().sum())

    isim    yas    not
0  False  False  False
1  False  False  False
2  False  False   True
3  False  False  False
4  False  False  False
isim    0
yas     0
not     1
dtype: int64

In [ ]:
#benzersiz değerler
print(df["yas"].unique())
print(df["yas"].nunique())
print(df.value_counts())

[25 30 22 28 27]
5
isim    yas  not
ali     25   80.0    1
ayşe    30   90.0    1
burak   27   85.0    1
zeynep  28   95.0    1
Name: count, dtype: int64

In [ ]:
df["yas"].value_counts()

yas
25    1
30    1
22    1
28    1
27    1
Name: count, dtype: int64

## Veri Seçme ve Filtreleme

In [ ]:
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
print(f"Notu 85 den büyük olanlar: \n {df[df["not"] > 85]}")
print(f"Yaşı 25 olanlar: \n {df[df["yas"] == 25]}")

Notu 85 den büyük olanlar:
      isim  yas  not
1    ayşe   30   90
3  zeynep   28   95
Yaşı 25 olanlar:
   isim  yas  not
0  ali   25   80

In [ ]:
#boolean maskeler
mask = df["not"] > 85
df[mask]

     isim  yas  not
1    ayşe   30   90
3  zeynep   28   95

In [ ]:
#çoklu koşullar
# 50 <= not <= 90
print(f"Orta başarı: \n {df[(df["not"] >= 50) & (df["not"] <= 90)]}")

Orta başarı:
      isim  yas  not
0     ali   25   80
1    ayşe   30   90
2  mehmet   22   75
4   burak   27   85

## Veri Temizleme

In [ ]:
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,None,22,None,27],
    "not":[80,90,None,95,85]
}
df = pd.DataFrame(data)
df.isnull()

    isim    yas    not
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4  False  False  False

In [ ]:
df.dropna() #silme

    isim   yas   not
0    ali  25.0  80.0
4  burak  27.0  85.0

In [ ]:
df.fillna(0) #eksik veri doldurma

     isim   yas   not
0     ali  25.0  80.0
1    ayşe   0.0  90.0
2  mehmet  22.0   0.0
3  zeynep   0.0  95.0
4   burak  27.0  85.0

In [ ]:
df["yas"].fillna(df["yas"].mean())

0    25.000000
1    24.666667
2    22.000000
3    24.666667
4    27.000000
Name: yas, dtype: float64

In [ ]:
#yinelenen veriler
data = {
    "isim":["ali","ayşe","ali","zeynep","burak"],
    "yas":[25,None,25,None,27],
    "not":[80,90,80,None,85]
}
df = pd.DataFrame(data)
df.duplicated() #yinelenen değer kontrolu, satır satır bakıyor yani her şeyi aynı mı diye

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [ ]:
df.drop_duplicates()

     isim   yas   not
0     ali  25.0  80.0
1    ayşe   NaN  90.0
3  zeynep   NaN   NaN
4   burak  27.0  85.0

In [ ]:
#değer değiştirme
df.replace({"ali":"ali_isim"})

       isim   yas   not
0  ali_isim  25.0  80.0
1      ayşe   NaN  90.0
2  ali_isim  25.0  80.0
3    zeynep   NaN   NaN
4     burak  27.0  85.0

In [ ]:
data = {
    "isim":[" ali","Ayse","mehmet","zeYnep","burak"],
    "yas":[25,21,22,23,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
df["isim"] = df["isim"].str.lower() #küçük harf yap
df["isim"] = df["isim"].str.strip() #boşluktan kurtul
df

     isim  yas  not
0     ali   25   80
1    ayse   21   90
2  mehmet   22   75
3  zeynep   23   95
4   burak   27   85

## Veri Dönüştürme

In [ ]:
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
df = df.sort_values(by = "not",ascending = False) #notlara göre sıralama

In [ ]:
#yeniden indeksleme
df = df.reindex([0,1,2,3,4])
df

     isim  yas  not
0     ali   25   80
1    ayşe   30   90
2  mehmet   22   75
3  zeynep   28   95
4   burak   27   85

In [ ]:
#tip dönüştürme
df.info()
df["not"] = df["not"].astype(float)
df["yas"] = df["yas"].astype(str)
df

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   isim    5 non-null      object
 1   yas     5 non-null      int64
 2   not     5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

     isim yas   not
0     ali  25  80.0
1    ayşe  30  90.0
2  mehmet  22  75.0
3  zeynep  28  95.0
4   burak  27  85.0

In [ ]:
#kategorik veri ekle
df["sehir"] = ["ankara","izmir","antalya","konya","istanbul"]
df["sehir"] = df["sehir"].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   isim    5 non-null      object
 1   yas     5 non-null      object
 2   not     5 non-null      float64
 3   sehir   5 non-null      category
dtypes: category(1), float64(1), object(2)
memory usage: 377.0+ bytes

## Gruplama ve Özetleme

In [ ]:
#temel gruplama
data = {
    "departman": ["IT","IT","HR","HR","Muhasebe","IT"],
    "personel" : ["ali","ayşe","mehmet","zeynep","burak","can"],
    "maaş" : [1222,1333,1444,1414,8666,1279]
    }
df = pd.DataFrame(data)
df.groupby("departman")["maaş"].mean()

departman
HR          1429.0
IT          1278.0
Muhasebe    8666.0
Name: maaş, dtype: float64

In [ ]:
#toplama, ortalama ve sayma
df.groupby("departman")["maaş"].sum() #toplam maaş

departman
HR          2858
IT          3834
Muhasebe    8666
Name: maaş, dtype: int64

In [ ]:
df.groupby("departman")["maaş"].count() #kişi sayısı

departman
HR          2
IT          3
Muhasebe    1
Name: maaş, dtype: int64

In [ ]:
# birden fazla sütuna göre gruplama
data = {
    "departman": ["IT","IT","HR","HR","Muhasebe","IT"],
    "personel" : ["ali","ayşe","mehmet","zeynep","burak","can"],
    "sehir" : ["Ankara","İstanbul","Rize","Rize","İstanbul","Rize"],
    "maaş" : [1222,1333,1444,1414,8666,1279]
    }
df = pd.DataFrame(data)
df.groupby(["departman","sehir"])["maaş"].mean()

departman  sehir
HR         Rize        1429.0
IT         Ankara      1222.0
           Rize        1279.0
           İstanbul    1333.0
Muhasebe   İstanbul    8666.0
Name: maaş, dtype: float64

In [ ]:
#agg()
df.groupby("departman")["maaş"].agg(["min","max","mean"])

            min   max    mean
departman
HR         1414  1444  1429.0
IT         1222  1333  1278.0
Muhasebe   8666  8666  8666.0

## Birleştirme ve Bir Araya Getirme

In [ ]:
#merge
df1 = pd.DataFrame({"id":[1,2,3],"isim":["Ali","Ayşe","Mehmet"]})
df2 = pd.DataFrame({"id":[1,2,4],"şehir":["Ankara","İstanbul","İzmir"]})
df_merge = pd.merge(df1,df2,on="id",how="inner") #ortak olan kayıtlar
df_merge

   id  isim     şehir
0   1   Ali    Ankara
1   2  Ayşe  İstanbul

In [ ]:
df_merge = pd.merge(df1,df2,on="id",how="left") #soldaki veriseti için tüm kayıtlar
df_merge

   id    isim     şehir
0   1     Ali    Ankara
1   2    Ayşe  İstanbul
2   3  Mehmet       NaN

In [ ]:
df_merge = pd.merge(df1,df2,on="id",how="right") #sağdaki veriseti için tüm kayıtlar
df_merge

   id  isim     şehir
0   1   Ali    Ankara
1   2  Ayşe  İstanbul
2   4   NaN     İzmir

In [ ]:
#indeks bazlı birleştirme
df1 = pd.DataFrame({"isim":["Ali","Ayşe","Mehmet"]},index=["a","b","c"])
df2 = pd.DataFrame({"not": [85,90,75]},index=["a","b","d"])

pd.merge(df1,df2,left_index=True,right_index=True,how="outer") # her iki tarafın tüm kayıtları gelir

     isim   not
a     Ali  85.0
b    Ayşe  90.0
c  Mehmet   NaN
d     NaN  75.0